language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.2.*"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/http-kernel:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/yaml:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/monolog-bridge:$SYMFONY_VERSION symfony/doctrine-bridge:$SYMFONY_VERSION; fi

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
